import React from 'react';
import { Rocket, Code, Terminal, Settings, ExternalLink, Key } from 'lucide-react';
import { GeneratedPersona } from '../types';
import { CopyButton } from './CopyButton';

interface DeploymentGuideProps {
  persona: GeneratedPersona;
}

export const DeploymentGuide: React.FC<DeploymentGuideProps> = ({ persona }) => {
  const codeSnippet = `
const { Bot } = require("grammy");
const { GoogleGenAI } = require("@google/genai");

// --- CONFIGURATION START ---

// 1. Get this from @BotFather
const TELEGRAM_TOKEN = "PASTE_YOUR_TELEGRAM_TOKEN_HERE";

// 2. Get this from https://aistudio.google.com/app/apikey
const GEMINI_API_KEY = "PASTE_YOUR_GEMINI_API_KEY_HERE";

// --- CONFIGURATION END ---

// System Instruction (Generated by BotPersona Forge)
const SYSTEM_INSTRUCTION = \`${persona.systemInstruction.replace(/`/g, '\\`')}\`;

const bot = new Bot(TELEGRAM_TOKEN);
const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

// Handle Messages
bot.on("message:text", async (ctx) => {
  try {
    await ctx.replyWithChatAction("typing");

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: ctx.message.text,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
      },
    });

    await ctx.reply(response.text);
  } catch (error) {
    console.error("Error:", error);
    await ctx.reply("I'm having trouble thinking right now.");
  }
});

// Start the Bot
bot.start();
console.log("Bot is running...");
`;

  return (
    <div className="space-y-6 animate-fade-in-up delay-100">
      <div className="flex items-center space-x-2 mb-4">
        <h3 className="text-xl font-bold text-white">3. Deployment Guide</h3>
        <div className="h-px flex-1 bg-slate-800"></div>
      </div>

      <div className="bg-slate-800/50 rounded-xl border border-slate-700 overflow-hidden">
        <div className="p-6 space-y-8">
          
          {/* Step 1: BotFather */}
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-600/20 text-blue-400 flex items-center justify-center font-bold border border-blue-600/30">1</div>
            <div className="space-y-2 flex-1">
              <h4 className="font-semibold text-white flex items-center gap-2">
                Create Bot & Get Token
                <ExternalLink className="w-4 h-4 text-slate-500" />
              </h4>
              <p className="text-slate-400 text-sm">
                Open <a href="https://t.me/BotFather" target="_blank" rel="noreferrer" className="text-blue-400 hover:underline">@BotFather</a> in Telegram.
              </p>
              <ul className="list-disc list-inside text-sm text-slate-400 space-y-1 ml-2">
                <li>Type <code className="bg-slate-900 px-1 rounded">/newbot</code> and follow instructions.</li>
                <li>Copy the <strong>HTTP API Token</strong> provided.</li>
              </ul>
            </div>
          </div>

          {/* Step 2: Configuration */}
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-purple-600/20 text-purple-400 flex items-center justify-center font-bold border border-purple-600/30">2</div>
            <div className="space-y-2 flex-1">
              <h4 className="font-semibold text-white">Apply Bot Settings</h4>
              <p className="text-slate-400 text-sm">
                Use the text generated in the <strong>Configuration</strong> section above.
              </p>
              <ul className="list-disc list-inside text-sm text-slate-400 space-y-1 ml-2">
                <li><code className="bg-slate-900 px-1 rounded">/setdescription</code> - Paste the Description.</li>
                <li><code className="bg-slate-900 px-1 rounded">/setabouttext</code> - Paste the About Text.</li>
                <li><code className="bg-slate-900 px-1 rounded">/setcommands</code> - Paste the Command List.</li>
              </ul>
            </div>
          </div>

          {/* Step 3: Code */}
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-green-600/20 text-green-400 flex items-center justify-center font-bold border border-green-600/30">3</div>
            <div className="space-y-3 flex-1">
              <h4 className="font-semibold text-white">Run the Server</h4>
              
              <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-4 mb-4">
                <h5 className="text-amber-400 text-sm font-semibold flex items-center gap-2 mb-2">
                  <Key className="w-4 h-4" />
                  Where to add the API Key?
                </h5>
                <p className="text-xs text-amber-200/80 mb-2">
                   You need to paste your keys directly into the code below (lines 7 and 10).
                </p>
                 <a 
                  href="https://aistudio.google.com/app/apikey" 
                  target="_blank" 
                  rel="noreferrer"
                  className="text-xs text-blue-400 hover:text-blue-300 inline-flex items-center gap-1 hover:underline"
                >
                  Get a Gemini API Key here <ExternalLink className="w-3 h-3" />
                </a>
              </div>

              <p className="text-slate-400 text-sm">
                1. Create a file named <code className="text-green-300">bot.js</code><br/>
                2. Install dependencies:
              </p>
              <div className="bg-slate-950 rounded-lg p-3 border border-slate-800 flex justify-between items-center">
                <code className="text-sm text-slate-300 font-mono">npm install grammy @google/genai</code>
                <CopyButton text="npm install grammy @google/genai" />
              </div>
              
              <p className="text-slate-400 text-sm mt-2">
                3. Copy the code below and replace the <span className="text-red-400">PASTE_..._HERE</span> placeholders:
              </p>
              <div className="relative group">
                 <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity z-10">
                    <CopyButton text={codeSnippet} label="Copy Code" />
                </div>
                <div className="bg-slate-950 rounded-lg p-4 border border-slate-800 overflow-x-auto">
                  <pre className="text-xs text-slate-300 font-mono leading-relaxed">
                    {codeSnippet}
                  </pre>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};